### ISSUE TITLE
Is there a way to hold a key (without holding it)

### ISSUE THREAD

**Issue by trieloff** [defiant00/purple#3]
I've started to implement the `artsey` layout for the Pimoroni keybow and I'm trying to use it on macOS.

One common shortcut I cannot express is the "Hold command (GUI) and press Tab repeatedly" gesture, which will tab through running applications. The regular GUI + TAB action just switches between the last two apps.

I've tried `Lock()` which mixes GUI in with every TAB, but does not keep it held and `hold=True`, but this is for allowing me to hold the key, not holding the key for me.

**Comment by defiant00** [comment]
You're right, there is not currently a way to have a key stay held without physically holding it.

I do like the idea of being able to toggle a key's state without having to hold it, so I'll be looking at adding this. However, due to other commitments, I can't make any specific guarantees as to when it might be ready. I do hope to have some free time around the end of the year, though.

Alternately, if you give it a go, a PR would always be welcome.

**Comment by trieloff** [comment]
Got it. I've created a PR, but would be grateful for guidance, my Python experience is more than a decade outdated and familiarity with the CircutPython is nil.

**Comment by defiant00** [comment]
Thanks again for this and the PR! This should now work with the new `Hold` action, which is based on your PR.
